# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'MyHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyHouse
pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
pod 'DSToast'
pod 'ReactiveObjC'
pod 'LookinServer', :configurations => ['Debug']
end
